version = 0.1

[default.deploy.parameters]
stack_name = "maya-analytics-meridix"
resolve_s3 = true
s3_prefix = "maya-analytics-meridix"
region = "eu-central-1"
profile = "Neuralect_Maya_share"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\" ProjectName=\"ProjectAnalytics\""
confirm_changeset = true
image_repositories = []

[default.build.parameters]
use_container = true
